services:
  mysql:
    image: mysql:8.0.39
    container_name: mysql8.0.39_it4409_shop
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: it4409_shop
    ports:
      - '5001:3306'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data_it4409_shop:/var/lib/mysql

volumes:
  mysql_data_it4409_shop:
