services:
    mysql:
        image: mysql:8.0.39
        container_name: mysql8.0.39
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: it4409_shop
        ports:
            - '5001:3306'
        volumes:
            - mysql_data:/var/lib/mysql

volumes:
    mysql_data:
